In [ ]:
import pandas as pd


teams_data = {
    'team_id': [1, 2, 3],
    'team_name': ['Mumbai Indians', 'Chennai Super Kings', 'Royal Challengers Bangalore'],
    'city': ['Mumbai', 'Chennai', 'Bangalore'],
    'coach_name': ['Mark Boucher', 'Stephen Fleming', 'Andy Flower']
}
teams = pd.DataFrame(teams_data)

players_data = {
    'player_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'player_name': ['Rohit Sharma', 'Jasprit Bumrah', 'Hardik Pandya', 'MS Dhoni', 'Ravindra Jadeja', 'Virat Kohli', 'Mohammed Siraj', 'Glenn Maxwell'],
    'age': [36, 30, 30, 42, 35, 35, 29, 35],
    'role': ['batsman', 'bowler', 'all-rounder', 'wicket-keeper', 'all-rounder', 'batsman', 'bowler', 'all-rounder'],
    'team_id': [1, 1, 1, 2, 2, 3, 3, 3]
}
players = pd.DataFrame(players_data)

print("Teams Table:")
display(teams)
print("\nPlayers Table:")
display(players)

Teams Table:

   team_id                    team_name       city       coach_name
0        1               Mumbai Indians     Mumbai     Mark Boucher
1        2          Chennai Super Kings    Chennai  Stephen Fleming
2        3  Royal Challengers Bangalore  Bangalore      Andy Flower

Players Table:

   player_id      player_name  age           role  team_id
0        101     Rohit Sharma   36        batsman        1
1        102   Jasprit Bumrah   30         bowler        1
2        103    Hardik Pandya   30    all-rounder        1
3        104         MS Dhoni   42  wicket-keeper        2
4        105  Ravindra Jadeja   35    all-rounder        2
5        106      Virat Kohli   35        batsman        3
6        107   Mohammed Siraj   29         bowler        3
7        108    Glenn Maxwell   35    all-rounder        3

In [ ]:

young_players = players[players['age'] < 32]
display(young_players)

   player_id     player_name  age         role  team_id
1        102  Jasprit Bumrah   30       bowler        1
2        103   Hardik Pandya   30  all-rounder        1
6        107  Mohammed Siraj   29       bowler        3

In [ ]:

young_bowlers = players[(players['role'] == 'bowler') & (players['age'] < 32)]
display(young_bowlers)

   player_id     player_name  age    role  team_id
1        102  Jasprit Bumrah   30  bowler        1
6        107  Mohammed Siraj   29  bowler        3

In [ ]:

projected_players = players[['player_name', 'role']]
display(projected_players)

       player_name           role
0     Rohit Sharma        batsman
1   Jasprit Bumrah         bowler
2    Hardik Pandya    all-rounder
3         MS Dhoni  wicket-keeper
4  Ravindra Jadeja    all-rounder
5      Virat Kohli        batsman
6   Mohammed Siraj         bowler
7    Glenn Maxwell    all-rounder

In [ ]:

all_rounders_info = players[players['role'] == 'all-rounder'][['player_name', 'age']]
display(all_rounders_info)

       player_name  age
2    Hardik Pandya   30
4  Ravindra Jadeja   35
7    Glenn Maxwell   35

## Part C — Set Operations
Union, Intersection, and Set Difference using the MI 2023 and 2024 squads.

In [ ]:

mi_2023 = pd.DataFrame({'player_name': ['Rohit Sharma', 'Jasprit Bumrah', 'Jofra Archer'], 'role': ['batsman', 'bowler', 'bowler']})
mi_2024 = pd.DataFrame({'player_name': ['Rohit Sharma', 'Jasprit Bumrah', 'Hardik Pandya'], 'role': ['batsman', 'bowler', 'all-rounder']})

union_df = pd.concat([mi_2023, mi_2024]).drop_duplicates()
intersection_df = pd.merge(mi_2023, mi_2024, how='inner')
merged = mi_2023.merge(mi_2024, on=['player_name', 'role'], how='left', indicator=True)
set_diff_df = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)

print("UNION (All Players):"); display(union_df)
print("\nINTERSECTION (Loyalists):"); display(intersection_df)
print("\nSET DIFFERENCE (Released Players):"); display(set_diff_df)

UNION (All Players):

      player_name         role
0    Rohit Sharma      batsman
1  Jasprit Bumrah       bowler
2    Jofra Archer       bowler
2   Hardik Pandya  all-rounder

INTERSECTION (Loyalists):

      player_name     role
0    Rohit Sharma  batsman
1  Jasprit Bumrah   bowler

SET DIFFERENCE (Released Players):

    player_name    role
2  Jofra Archer  bowler

## Part D + E — Join and Aggregation
Cartesian products, Equality conditions, and Aggregations (Count, Avg, Max).

In [ ]:

cartesian_product = players.merge(teams, how='cross')
print(f"Total rows: {len(cartesian_product)}")
display(cartesian_product.head(10))

Total rows: 24

,player_id,player_name,age,role,team_id_x,team_id_y,team_name,city,coach_name
0,101,Rohit Sharma,36,batsman,1,1,Mumbai Indians,Mumbai,Mark Boucher
1,101,Rohit Sharma,36,batsman,1,2,Chennai Super Kings,Chennai,Stephen Fleming
2,101,Rohit Sharma,36,batsman,1,3,Royal Challengers Bangalore,Bangalore,Andy Flower
3,102,Jasprit Bumrah,30,bowler,1,1,Mumbai Indians,Mumbai,Mark Boucher
4,102,Jasprit Bumrah,30,bowler,1,2,Chennai Super Kings,Chennai,Stephen Fleming
5,102,Jasprit Bumrah,30,bowler,1,3,Royal Challengers Bangalore,Bangalore,Andy Flower
6,103,Hardik Pandya,30,all-rounder,1,1,Mumbai Indians,Mumbai,Mark Boucher
7,103,Hardik Pandya,30,all-rounder,1,2,Chennai Super Kings,Chennai,Stephen Fleming
8,103,Hardik Pandya,30,all-rounder,1,3,Royal Challengers Bangalore,Bangalore,Andy Flower
9,104,MS Dhoni,42,wicket-keeper,2,1,Mumbai Indians,Mumbai,Mark Boucher

In [ ]:

joined_df = pd.merge(players, teams, on='team_id')
print(f"Total rows: {len(joined_df)}")
display(joined_df)

Total rows: 8

,player_id,player_name,age,role,team_id,team_name,city,coach_name
0,101,Rohit Sharma,36,batsman,1,Mumbai Indians,Mumbai,Mark Boucher
1,102,Jasprit Bumrah,30,bowler,1,Mumbai Indians,Mumbai,Mark Boucher
2,103,Hardik Pandya,30,all-rounder,1,Mumbai Indians,Mumbai,Mark Boucher
3,104,MS Dhoni,42,wicket-keeper,2,Chennai Super Kings,Chennai,Stephen Fleming
4,105,Ravindra Jadeja,35,all-rounder,2,Chennai Super Kings,Chennai,Stephen Fleming
5,106,Virat Kohli,35,batsman,3,Royal Challengers Bangalore,Bangalore,Andy Flower
6,107,Mohammed Siraj,29,bowler,3,Royal Challengers Bangalore,Bangalore,Andy Flower
7,108,Glenn Maxwell,35,all-rounder,3,Royal Challengers Bangalore,Bangalore,Andy Flower

In [ ]:

pipeline_result = pd.merge(players, teams, on='team_id') \
                    [players['role'] == 'bowler'] \
                    [['player_name', 'city']] \
                    .rename(columns={'player_name': 'Bowler Name', 'city': 'Franchise City'})
display(pipeline_result)

      Bowler Name Franchise City
1  Jasprit Bumrah         Mumbai
6  Mohammed Siraj      Bangalore

In [ ]:

players_per_team = joined_df.groupby('team_name')['player_id'].count().reset_index(name='Player Count')
avg_age = joined_df.groupby('team_name')['age'].mean().reset_index(name='Average Age')
oldest = players[players['age'] == players['age'].max()]

print("COUNT:"); display(players_per_team)
print("\nAVG:"); display(avg_age)
print("\nMAX:"); display(oldest)

COUNT:

                     team_name  Player Count
0          Chennai Super Kings             2
1               Mumbai Indians             3
2  Royal Challengers Bangalore             3

AVG:

                     team_name  Average Age
0          Chennai Super Kings         38.5
1               Mumbai Indians         32.0
2  Royal Challengers Bangalore         33.0

MAX:

   player_id player_name  age           role  team_id
3        104    MS Dhoni   42  wicket-keeper        2

## Your Turn — Cell 11 Challenge
Task: Find the team with the most all-rounders using Select, Join, and Aggregation.